// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2C2pwIk4UyXZousj-p4SJg54Dy8t_4A',
    appId: '1:103918647242:web:a4598518c5fed3dd0b8133',
    messagingSenderId: '103918647242',
    projectId: 'pim-candy-crush-b6b75',
    authDomain: 'pim-candy-crush-b6b75.firebaseapp.com',
    storageBucket: 'pim-candy-crush-b6b75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFKNE2uTFwDUaI-QK5rzSDv8M2GB9a3k',
    appId: '1:103918647242:android:8e8fef894a52ae970b8133',
    messagingSenderId: '103918647242',
    projectId: 'pim-candy-crush-b6b75',
    storageBucket: 'pim-candy-crush-b6b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt_jvrnfch5znW_2RwRFv4tWgCkGzdlfU',
    appId: '1:103918647242:ios:b4edd19a78c3e9cb0b8133',
    messagingSenderId: '103918647242',
    projectId: 'pim-candy-crush-b6b75',
    storageBucket: 'pim-candy-crush-b6b75.appspot.com',
    androidClientId: '103918647242-plqino9ut7ilok8ekn67nnllbblaed2m.apps.googleusercontent.com',
    iosClientId: '103918647242-l93o152be1lt63ccggq42rk0cjb03r1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.candyCrush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt_jvrnfch5znW_2RwRFv4tWgCkGzdlfU',
    appId: '1:103918647242:ios:b4edd19a78c3e9cb0b8133',
    messagingSenderId: '103918647242',
    projectId: 'pim-candy-crush-b6b75',
    storageBucket: 'pim-candy-crush-b6b75.appspot.com',
    androidClientId: '103918647242-plqino9ut7ilok8ekn67nnllbblaed2m.apps.googleusercontent.com',
    iosClientId: '103918647242-l93o152be1lt63ccggq42rk0cjb03r1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.candyCrush',
  );
}
